services:
  - type: web
    name: kredox-ai-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: CLOUDINARY_FOLDER
        value: kredox-ai-demo
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: DOMAIN
        sync: false

  - type: web
    name: kredox-ai-ml
    env: python
    plan: free
    rootDir: ml
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
